volumes:
  test-vol:

services:

  pgsql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password # environment variable that sets the superuser password for PostgreSQL
      POSTGRES_USER: postgres # variable that will create the specified user with superuser power and a database with the same name
      POSTGRES_DB: flask
    volumes:
      - test-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432